stages:
#  - test
  - compile
  - build-container

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE
  GOPRIVATE: gitlab.offis.de
# --- api-gateway ---
compile-gateway:
  stage: compile
  image: golang:alpine
  tags:
    - lab
  rules:
    - changes:
       - middleware/gateway/**/*
  script:
    - echo $GOPRIVATE
    - echo "machine gitlab.offis.de" >> ~/.netrc
    - echo "login $CI_REGISTRY_USER" >> ~/.netrc
    - echo "password $CI_REGISTRY_PASSWORD" >> ~/.netrc
#    - cat ~/.netrc
    - apk update && apk add alpine-sdk
    - cd middleware/gateway/cmd
    - go get -v
    - cd ..
    - go build -o dist/main cmd/main.*go
  artifacts:
    expire_in: 1 day
    paths:
      - middleware/gateway/dist/

build-api-gateway:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - middleware/gateway/**/*
  needs:
    - job: compile-gateway
      artifacts: true
  artifacts:
    expire_in: 1 day
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  script:
    - sed -i "s/<cert_dir>/\/srv\/config\/certs/g" deploy/create-cert.sh
    - sed -i "s/<cert_file>/\/srv\/config\/certs\/cert.pem/g" deploy/create-cert.sh
    - sed -i "s/<key_file>/\/srv\/config\/certs\/key.pem/g" deploy/create-cert.sh
    - mv deploy/create-cert.sh middleware/gateway/create-cert.sh
    - echo "Start container build for $IMAGE_TAG/gateway:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/gateway:$CI_COMMIT_REF_SLUG -f deploy/gateway.containerfile middleware/gateway
    - podman push $IMAGE_TAG/gateway:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY
# --- mqtt-error-injection-engine ---
compile-mqtt-error-injection-engine:
  stage: compile
  image: golang:alpine
  tags:
    - lab
  rules:
    - changes:
       - middleware/mqtt-error-injection-engine/**/*
  script:
    - apk update && apk add alpine-sdk
    - cd middleware/mqtt-error-injection-engine/cmd
    - go get
    - cd ..
    - go build -o dist/main cmd/main.*go
#    - mv create-cert.sh dist 
  artifacts:
    expire_in: 1 day
    paths:
      - middleware/mqtt-error-injection-engine/dist/

build-mqtt-error-injection-engine:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - middleware/mqtt-error-injection-engine/**/*
  needs:
    - job: compile-mqtt-error-injection-engine
      artifacts: true
  artifacts:
    expire_in: 1 day
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  script:
    - sed -i "s/<cert_dir>/\/srv\/config\/certs/g" deploy/create-cert.sh
    - sed -i "s/<cert_file>/\/srv\/config\/certs\/cert.pem/g" deploy/create-cert.sh
    - sed -i "s/<key_file>/\/srv\/config\/certs\/key.pem/g" deploy/create-cert.sh
    - mv deploy/create-cert.sh middleware/mqtt-error-injection-engine/create-cert.sh
    - echo "Start container build for $IMAGE_TAG/mqtt-error-injection-engine:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/mqtt-error-injection-engine:$CI_COMMIT_REF_SLUG -f deploy/mqtt-error-injection-engine.containerfile middleware/mqtt-error-injection-engine
    - podman push $IMAGE_TAG/mqtt-error-injection-engine:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY
# --- user-management ---
compile-user-management:
  stage: compile
  image: golang:alpine
  tags:
    - lab
  rules:
    - changes:
       - middleware/user-management/**/*
  script:
    - echo "machine gitlab.offis.de" >> ~/.netrc
    - echo "login $CI_REGISTRY_USER" >> ~/.netrc
    - echo "password $CI_REGISTRY_PASSWORD" >> ~/.netrc
    - apk update && apk add alpine-sdk
    - cd middleware/user-management/cmd
    - go get -v
    - cd ..
    - go build -o dist/main cmd/main.*go
  artifacts:
    expire_in: 1 day
    paths:
      - middleware/user-management/dist/

build-user-management:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - middleware/user-management/**/*
  needs:
    - job: compile-user-management
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  script:
    - sed -i "s/<cert_dir>/\/srv\/config\/certs/g" deploy/create-cert.sh
    - sed -i "s/<cert_file>/\/srv\/config\/certs\/cert.pem/g" deploy/create-cert.sh
    - sed -i "s/<key_file>/\/srv\/config\/certs\/key.pem/g" deploy/create-cert.sh
    - mv deploy/create-cert.sh middleware/user-management/create-cert.sh
    - echo "Start container build for $IMAGE_TAG/user-management:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/user-management:$CI_COMMIT_REF_SLUG -f deploy/user-management.containerfile middleware/user-management
    - podman push $IMAGE_TAG/user-management:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY
# --- researcher frontend ---
compile-researcher-frontend:
  stage: compile
  image: node:20.11-alpine3.18
  tags:
    - lab
  rules:
    - changes:
       - representation/researcher_frontend/**/*
  script:
    - apk update
    - cd representation/researcher_frontend
    - npm install --save
    - npm run build
  artifacts:
    name: "web"
    expire_in: 1 day
    paths:
      - representation/researcher_frontend/dist/

build-container-researcher-frontend:
  stage:
    build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - representation/researcher_frontend/**/*
  needs:
    - job: compile-researcher-frontend
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  artifacts:
    expire_in: 1 day
  script:
    - sed -i "s/<cert_dir>/\/usr\/local\/nginx\/conf/g" deploy/create-cert.sh
    - sed -i "s/<cert_file>/\/usr\/local\/nginx\/conf\/cert.pem/g" deploy/create-cert.sh
    - sed -i "s/<key_file>/\/usr\/local\/nginx\/conf\/key.pem/g" deploy/create-cert.sh
    - mv deploy/create-cert.sh representation/researcher_frontend/create-cert.sh
    - echo "Start container build for $IMAGE_TAG/researcher-frontend:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/researcher-frontend:$CI_COMMIT_REF_SLUG -f deploy/researcher-frontend.containerfile representation/researcher_frontend
    - podman push $IMAGE_TAG/researcher-frontend:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY

build-ingress:
  stage:
    build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  artifacts:
    expire_in: 1 day
  script:
    - sed -i "s/<cert_dir>/\/usr\/local\/nginx\/conf/g" deploy/create-cert.sh
    - sed -i "s/<cert_file>/\/usr\/local\/nginx\/conf\/cert.pem/g" deploy/create-cert.sh
    - sed -i "s/<key_file>/\/usr\/local\/nginx\/conf\/key.pem/g" deploy/create-cert.sh
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/nginx-ingress:$CI_COMMIT_REF_SLUG -f deploy/ingress.containerfile deploy
    - podman push $IMAGE_TAG/nginx-ingress:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY 
#--- Experimental Artifacts Baseline ---
compile-experiment-ui-baseline:
  stage: compile
  image: node:20.11-alpine3.18
  tags:
    - lab
  rules:
    - changes:
       - experiment-ui/home-assistance-ui/**/*
  script:
    - apk update
    - cd experiment-ui/home-assistance-ui
    - npm install
    - sed -i "s/TEMPLATE/BaselineUI/g" App-template.tsx
    - mv App-template.tsx src/App.tsx
    - npm run build-vite
  artifacts:
    name: "web-baseline"
    expire_in: 1 day
    paths:
      - experiment-ui/home-assistance-ui/dist/

build-baseline:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - experiment-ui/home-assistance-ui/**/*
  needs:
    - job: compile-experiment-ui-baseline
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  artifacts:
    expire_in: 1 day
  script:
    - echo "Start container build for $IMAGE_TAG/baseline:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/baseline:$CI_COMMIT_REF_SLUG -f experiment-ui/home-assistance-ui/src/deploy/baseline.containerfile experiment-ui/home-assistance-ui
    - podman push $IMAGE_TAG/baseline:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY

#--- Experimental Artifacts StructualUI [!sic] ---
compile-experiment-ui-structual:
  stage: compile
  image: node:20.11-alpine3.18
  tags:
    - lab
  rules:
    - changes:
       - experiment-ui/home-assistance-ui/**/*
  script:
    - apk update
    - cd experiment-ui/home-assistance-ui
    - npm install --save
    - sed -i "s/TEMPLATE/StructualUI/g" App-template.tsx
    - mv App-template.tsx src/App.tsx
    - npm run build-vite
  artifacts:
    name: "web-structual"
    expire_in: 1 day
    paths:
      - experiment-ui/home-assistance-ui/dist/

build-structual:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - experiment-ui/home-assistance-ui/**/*
  needs:
    - job: compile-experiment-ui-structual
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  artifacts:
    expire_in: 1 day
  script:
    - echo "Start container build for $IMAGE_TAG/structual:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/structual:$CI_COMMIT_REF_SLUG -f experiment-ui/home-assistance-ui/src/deploy/baseline.containerfile experiment-ui/home-assistance-ui
    - podman push $IMAGE_TAG/structual:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY
#--- Experimental Artefact Contextual---
compile-experiment-ui-contextual:
  stage: compile
  image: node:20.11-alpine3.18
  tags:
    - lab
  rules:
    - changes:
       - experiment-ui/home-assistance-ui/**/*
  script:
    - apk update
    - cd experiment-ui/home-assistance-ui
    - npm install --save
    - sed -i "s/TEMPLATE/ContextualUI/g" App-template.tsx
    - mv App-template.tsx src/App.tsx
    - npm run build-vite
  artifacts:
    name: "web-structual"
    expire_in: 1 day
    paths:
      - experiment-ui/home-assistance-ui/dist/

build-contextual:
  stage: build-container
  image: quay.io/containers/podman:v5
  tags:
    - lab
  rules:
    - changes:
        - experiment-ui/home-assistance-ui/**/*
  needs:
    - job: compile-experiment-ui-contextual
      artifacts: true
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  artifacts:
    expire_in: 1 day
  script:
    - echo "Start container build for $IMAGE_TAG/contextual:$CI_COMMIT_REF_SLUG"
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -t $IMAGE_TAG/contextual:$CI_COMMIT_REF_SLUG -f experiment-ui/home-assistance-ui/src/deploy/baseline.containerfile experiment-ui/home-assistance-ui
    - podman push $IMAGE_TAG/contextual:$CI_COMMIT_REF_SLUG
    - podman logout $CI_REGISTRY

