[request_definition]
r = sub, obj, attribute, act

[policy_definition]
p = sub_rule, act, eft, res

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && regexMatch(r.act, p.act)